version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres-container
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5431:5432'
