export enum typeAppointment {
  SESSION = 'SESSION',
  ADMINISTRATIVE_RECORDS = 'ADMINISTRATIVE_RECORDS',
  COLLECTIVE_ACTIVITIES = 'COLLECTIVE_ACTIVITIES',
}

export enum StatusApointment {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FINALIZED = 'FINALIZED',
  CANCELED = 'CANCELED',
  ABSENCE = 'ABSENCE',
}
