export enum psychologicalDisorder {
  DEPRESSION = 'DEPRESSION',
  GENERALIZED_ANXIETY = 'GENERALIZED_ANXIETY',
  BIPOLAR_DISORDER = 'BIPOLAR_DISORDER',
  BORDERLINE_PERSONALITY_DISORDER = 'BORDERLINE_PERSONALITY_DISORDER',
  SCHIZOPHRENIA = 'SCHIZOPHRENIA',
  OBSESSIVE_COMPULSIVE_DISORDER = 'OBSESSIVE_COMPULSIVE_DISORDER',
  POST_TRAUMATIC_STRESS_DISORDER = 'POST_TRAUMATIC_STRESS_DISORDER',
  ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER = 'ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER',
  AUTISM_SPECTRUM_DISORDER = 'AUTISM_SPECTRUM_DISORDER',
  EATING_DISORDER = 'EATING_DISORDER',
  SUBSTANCE_ABUSE = 'SUBSTANCE_ABUSE',
  PERSONALITY_DISORDER = 'PERSONALITY_DISORDER',
  DISSOCIATIVE_DISORDER = 'DISSOCIATIVE_DISORDER',
  BODY_DYSMORPHIC_DISORDER = 'BODY_DYSMORPHIC_DISORDER',
  PARANOID_DISORDER = 'PARANOID_DISORDER',
  PANIC_DISORDER = 'PANIC_DISORDER',
  PSYCHOSIS = 'PSYCHOSIS',
  OTHER = 'OTHER',
}

export enum Difficulty {
  AVALIATION = 'AVALIATION',
  ORGANIZATION = 'ORGANIZATION',
  CONCENTRATION = 'CONCENTRATION',
  MEMORY = 'MEMORY',
  TDAH = 'TDAH',
  COMUNICATION = 'COMUNICATION',
}

export enum Relationship {
  RELATIONSHIP_WITH_COLLEAGUES = 'RELATIONSHIP_WITH_COLLEAGUES',
  RELATIONSHIP_WITH_FAMILY = 'RELATIONSHIP_WITH_FAMILY',
  RELATIONSHIP_WITH_PARTNER = 'RELATIONSHIP_WITH_PARTNER',
  RELATIONSHIP_WITH_TEACHER = 'RELATIONSHIP_WITH_TEACHER',
  OTHER = 'OTHER',
}
